"""initial_schema

Revision ID: 66beba687ce3
Revises: 
Create Date: 2026-01-06 17:28:40.831884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66beba687ce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('language_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code')
    )
    op.create_index('ix_language_code', 'languages', ['language_code'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code')
    )
    op.create_index('ix_project_code', 'projects', ['project_code'], unique=False)
    op.create_table('project_languages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'language_id', name='uq_project_language')
    )
    op.create_index('ix_project_language_project', 'project_languages', ['project_id'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('parent_version_id', sa.String(), nullable=True),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('draft','locked','archived')", name='ck_version_status'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'status', name='uq_project_single_version_per_status')
    )
    op.create_index('ix_version_project', 'versions', ['project_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'name', name='uq_action_name_per_version')
    )
    op.create_index('ix_action_version', 'actions', ['version_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('entity_key', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('use_regex', sa.Boolean(), nullable=True),
    sa.Column('use_lookup', sa.Boolean(), nullable=True),
    sa.Column('influence_conversation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'entity_key', name='uq_entity_key_per_version')
    )
    op.create_index('ix_entity_version', 'entities', ['version_id'], unique=False)
    op.create_table('forms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('ignored_intents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'name', name='uq_form_name_per_version')
    )
    op.create_index('ix_form_version', 'forms', ['version_id'], unique=False)
    op.create_table('intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('intent_name', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'intent_name', name='uq_intent_name_per_version')
    )
    op.create_index('ix_intent_version', 'intents', ['version_id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'name', name='uq_response_name_per_version')
    )
    op.create_index('ix_response_version', 'responses', ['version_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'name', name='uq_rule_name_per_version')
    )
    op.create_index('ix_rule_version', 'rules', ['version_id'], unique=False)
    op.create_table('session_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('session_expiration_time', sa.Integer(), nullable=False),
    sa.Column('carry_over_slots_to_new_session', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', name='uq_session_config_per_version')
    )
    op.create_index('ix_session_config_version', 'session_configs', ['version_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('slot_type', sa.String(), nullable=False),
    sa.Column('influence_conversation', sa.Boolean(), nullable=True),
    sa.Column('initial_value', sa.String(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("slot_type IN ('text','bool','float','list','categorical','any')", name='ck_slot_type'),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'name', name='uq_slot_name_per_version')
    )
    op.create_index('ix_slot_version', 'slots', ['version_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'name', name='uq_story_name_per_version')
    )
    op.create_index('ix_story_version', 'stories', ['version_id'], unique=False)
    op.create_table('version_languages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'language_id', name='uq_version_language')
    )
    op.create_index('ix_version_language_version', 'version_languages', ['version_id'], unique=False)
    op.create_table('entity_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'group_name', name='uq_entity_group')
    )
    op.create_table('entity_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'role', name='uq_entity_role')
    )
    op.create_table('form_required_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'slot_id', name='uq_form_required_slot')
    )
    op.create_index('ix_form_required_slot_form', 'form_required_slots', ['form_id'], unique=False)
    op.create_table('intent_localizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id', 'language_id', name='uq_intent_language')
    )
    op.create_index('ix_localization_intent', 'intent_localizations', ['intent_id'], unique=False)
    op.create_table('lookups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('lookup_name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'lookup_name', name='uq_lookup_name_per_version')
    )
    op.create_index('ix_lookup_version', 'lookups', ['version_id'], unique=False)
    op.create_table('regexes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('regex_name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'regex_name', name='uq_regex_name_per_version')
    )
    op.create_index('ix_regex_version', 'regexes', ['version_id'], unique=False)
    op.create_table('response_variants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('response_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_response_variant_response', 'response_variants', ['response_id'], unique=False)
    op.create_table('rule_conditions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('slot_name', sa.String(), nullable=True),
    sa.Column('slot_value', sa.String(), nullable=True),
    sa.Column('active_loop', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("condition_type IN ('slot','active_loop')", name='ck_rule_condition_type'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_condition_rule', 'rule_conditions', ['rule_id'], unique=False)
    op.create_table('rule_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('intent_id', sa.String(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('response_id', sa.String(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('active_loop_value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("step_type IN ('intent','action','active_loop','slot')", name='ck_rule_step_type'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_step_rule', 'rule_steps', ['rule_id'], unique=False)
    op.create_table('slot_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('not_intent', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('active_loop', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("mapping_type IN ('from_entity','from_text','from_intent','from_trigger_intent','custom')", name='ck_slot_mapping_type'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slot_mapping_slot', 'slot_mappings', ['slot_id'], unique=False)
    op.create_table('story_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('timeline_index', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(), nullable=False),
    sa.Column('intent_id', sa.String(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('response_id', sa.String(), nullable=True),
    sa.Column('form_id', sa.String(), nullable=True),
    sa.Column('active_loop_value', sa.String(), nullable=True),
    sa.Column('checkpoint_name', sa.String(), nullable=True),
    sa.Column('or_group_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("step_type IN ('intent','action','slot','active_loop','checkpoint','or')", name='ck_story_step_type'),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_step_or_group', 'story_steps', ['or_group_id'], unique=False)
    op.create_index('ix_step_story', 'story_steps', ['story_id'], unique=False)
    op.create_table('synonyms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('canonical_value', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'canonical_value', 'entity_id', name='uq_synonym_per_version_entity')
    )
    op.create_index('ix_synonym_version', 'synonyms', ['version_id'], unique=False)
    op.create_table('form_slot_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('form_required_slot_id', sa.String(), nullable=False),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('not_intent', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.CheckConstraint("mapping_type IN ('from_entity','from_text','from_intent','from_trigger_intent')", name='ck_form_slot_mapping_type'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['form_required_slot_id'], ['form_required_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_form_slot_mapping_frs', 'form_slot_mappings', ['form_required_slot_id'], unique=False)
    op.create_table('intent_examples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('intent_localization_id', sa.String(), nullable=False),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['intent_localization_id'], ['intent_localizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_example_localization', 'intent_examples', ['intent_localization_id'], unique=False)
    op.create_table('lookup_examples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lookup_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['lookup_id'], ['lookups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_id', 'language_id', 'example', name='uq_lookup_example_per_language')
    )
    op.create_index('ix_lookup_example_lookup', 'lookup_examples', ['lookup_id'], unique=False)
    op.create_table('regex_examples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('regex_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['regex_id'], ['regexes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regex_id', 'language_id', 'example', name='uq_regex_example_per_language')
    )
    op.create_index('ix_regex_example_regex', 'regex_examples', ['regex_id'], unique=False)
    op.create_table('response_components',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('response_variant_id', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("component_type IN ('text', 'buttons', 'image', 'custom', 'attachment')", name='ck_response_component_type'),
    sa.ForeignKeyConstraint(['response_variant_id'], ['response_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_response_component_variant', 'response_components', ['response_variant_id'], unique=False)
    op.create_table('response_conditions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('response_variant_id', sa.String(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('slot_name', sa.String(), nullable=True),
    sa.Column('slot_value', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("condition_type IN ('slot', 'active_loop')", name='ck_response_condition_type'),
    sa.ForeignKeyConstraint(['response_variant_id'], ['response_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_response_condition_variant', 'response_conditions', ['response_variant_id'], unique=False)
    op.create_table('rule_slot_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_step_id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_step_id'], ['rule_steps.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_slot_event_step', 'rule_slot_events', ['rule_step_id'], unique=False)
    op.create_table('rule_step_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_step_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['rule_step_id'], ['rule_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rule_step_entity_step', 'rule_step_entities', ['rule_step_id'], unique=False)
    op.create_table('story_slot_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_step_id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.ForeignKeyConstraint(['story_step_id'], ['story_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_slot_event_step', 'story_slot_events', ['story_step_id'], unique=False)
    op.create_table('story_step_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('story_step_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['story_step_id'], ['story_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_step_entity_step', 'story_step_entities', ['story_step_id'], unique=False)
    op.create_table('synonym_examples',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('synonym_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['synonym_id'], ['synonyms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('synonym_id', 'language_id', 'example', name='uq_synonym_example_per_language')
    )
    op.create_index('ix_synonym_example_synonym', 'synonym_examples', ['synonym_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_synonym_example_synonym', table_name='synonym_examples')
    op.drop_table('synonym_examples')
    op.drop_index('ix_story_step_entity_step', table_name='story_step_entities')
    op.drop_table('story_step_entities')
    op.drop_index('ix_story_slot_event_step', table_name='story_slot_events')
    op.drop_table('story_slot_events')
    op.drop_index('ix_rule_step_entity_step', table_name='rule_step_entities')
    op.drop_table('rule_step_entities')
    op.drop_index('ix_rule_slot_event_step', table_name='rule_slot_events')
    op.drop_table('rule_slot_events')
    op.drop_index('ix_response_condition_variant', table_name='response_conditions')
    op.drop_table('response_conditions')
    op.drop_index('ix_response_component_variant', table_name='response_components')
    op.drop_table('response_components')
    op.drop_index('ix_regex_example_regex', table_name='regex_examples')
    op.drop_table('regex_examples')
    op.drop_index('ix_lookup_example_lookup', table_name='lookup_examples')
    op.drop_table('lookup_examples')
    op.drop_index('ix_example_localization', table_name='intent_examples')
    op.drop_table('intent_examples')
    op.drop_index('ix_form_slot_mapping_frs', table_name='form_slot_mappings')
    op.drop_table('form_slot_mappings')
    op.drop_index('ix_synonym_version', table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_index('ix_step_story', table_name='story_steps')
    op.drop_index('ix_step_or_group', table_name='story_steps')
    op.drop_table('story_steps')
    op.drop_index('ix_slot_mapping_slot', table_name='slot_mappings')
    op.drop_table('slot_mappings')
    op.drop_index('ix_rule_step_rule', table_name='rule_steps')
    op.drop_table('rule_steps')
    op.drop_index('ix_rule_condition_rule', table_name='rule_conditions')
    op.drop_table('rule_conditions')
    op.drop_index('ix_response_variant_response', table_name='response_variants')
    op.drop_table('response_variants')
    op.drop_index('ix_regex_version', table_name='regexes')
    op.drop_table('regexes')
    op.drop_index('ix_lookup_version', table_name='lookups')
    op.drop_table('lookups')
    op.drop_index('ix_localization_intent', table_name='intent_localizations')
    op.drop_table('intent_localizations')
    op.drop_index('ix_form_required_slot_form', table_name='form_required_slots')
    op.drop_table('form_required_slots')
    op.drop_table('entity_roles')
    op.drop_table('entity_groups')
    op.drop_index('ix_version_language_version', table_name='version_languages')
    op.drop_table('version_languages')
    op.drop_index('ix_story_version', table_name='stories')
    op.drop_table('stories')
    op.drop_index('ix_slot_version', table_name='slots')
    op.drop_table('slots')
    op.drop_index('ix_session_config_version', table_name='session_configs')
    op.drop_table('session_configs')
    op.drop_index('ix_rule_version', table_name='rules')
    op.drop_table('rules')
    op.drop_index('ix_response_version', table_name='responses')
    op.drop_table('responses')
    op.drop_index('ix_intent_version', table_name='intents')
    op.drop_table('intents')
    op.drop_index('ix_form_version', table_name='forms')
    op.drop_table('forms')
    op.drop_index('ix_entity_version', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_action_version', table_name='actions')
    op.drop_table('actions')
    op.drop_index('ix_version_project', table_name='versions')
    op.drop_table('versions')
    op.drop_index('ix_project_language_project', table_name='project_languages')
    op.drop_table('project_languages')
    op.drop_index('ix_project_code', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_language_code', table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
